In [1]:
import pandas as pd
import pandas_datareader.data as web
import numpy as np
import matplotlib.pyplot as plt
import datetime
from datetime import date
from datetime import timedelta
%matplotlib inline

In [5]:
today = datetime.date.today()
yesterday = today - timedelta(days=1)

def get_sp500_tickers():
    table=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
    df = table[0]
    df.to_csv("S&P500-Symbols.csv", columns=['Symbol'])
    return


def get_open_close(frame):
    cls = (web.DataReader(frame['Symbols'], data_source='yahoo', start=yesterday)['Close'])
    cls = cls.transpose().reindex()
    frame['Close'] = cls[str(yesterday)].values
    
    opn = (web.DataReader(frame['Symbols'], data_source='yahoo', start=today)['Open'])
    opn = opn.transpose().reindex()
    frame['Open'] = opn[str(today)].values
    
    return(frame)

def find_gaps(size, number_of_shares):
    today = datetime.date.today()
    yesterday = today - timedelta(days=1)
    
    print('Loading Ticker Data...')
    gap_frame = pd.read_csv("S&P500-Symbols.csv", nrows=number_of_shares)
    gap_frame.columns = ['Number', 'Symbols']
    del gap_frame['Number']
    
    print('Loading Open/Close Data...')
    gap_frame = test_get_open_close(gap_frame).set_index('Symbols')
    
    gap_frame['Perc Gap'] = (gap_frame['Open']-gap_frame['Close'])*100/gap_frame['Close']
    gap_frame = gap_frame[abs((gap_frame['Open']-gap_frame['Close'])*100/gap_frame['Close']) > size]
    
    return(gap_frame)

get_sp500_tickers()

In [3]:
find_gaps(3, 100)

C:\Users\Henry\anaconda3\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BRK.B', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
C:\Users\Henry\anaconda3\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BF.B', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

              Close        Open  Perc Gap
Symbols
APA       15.120000   15.800000  4.497357
CCL      117.489998  122.199997  4.008851

In [19]:
test_find_gaps(1, 10)

Loading Ticker Data...
Loading Open/Close Data...

              Close        Open  Perc Gap
Symbols
ABMD     341.859985  346.130005  1.249055
AES       24.809999   25.110001  1.209194

In [20]:
test_find_gaps(1, 500)

Loading Ticker Data...
Loading Open/Close Data...

C:\Users\Henry\anaconda3\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BRK.B', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
C:\Users\Henry\anaconda3\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BF.B', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

              Close        Open      Perc Gap
Symbols
ABMD     341.859985  346.130005      1.249055
AES       24.809999   25.110001      1.209194
AFL       45.610001   46.259998      1.425121
A          0.620000  122.500000  19658.064364
ALK       49.889999   50.849998      1.924232
...             ...         ...           ...
WY        21.290001   21.719999      2.019720
WMB      101.760002  103.750000      1.955580
WYNN      22.590000   22.820000      1.018148
XEL      135.309998  136.699997      1.027270
XRX       97.139999   98.389999      1.286803

[223 rows x 3 columns]

In [8]:
test_find_gaps(1, 20)

Loading Ticker Data...
Loading Open/Close Data...

              Close        Open      Perc Gap
Symbols
ABMD     341.859985  346.130005      1.249055
AES       24.809999   25.110001      1.209194
AFL       45.610001   46.259998      1.425121
A          0.620000  122.500000  19658.064364
ALK       49.889999   50.849998      1.924232
ALB      166.369995  169.449997      1.851296
ALGN     543.049988  551.780029      1.607594